using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UI;

[GenerateTypedNameReferences]
public sealed partial class MultiplayerMenu : DefaultWindow
{
    public MultiplayerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}