- type: entity
  id: BaseBlock
  abstract: true
  placement:
    mode: SnapgridCenter
  components:
    - type: Sprite
      state: full
      drawdepth: Blocks
    - type: Physics
      bodyType: Static
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5, -0.5, 0.5, 0.5"
          density: 100
          friction: 0
          mask:
            - BlockMask
          layer:
            - BlockLayer
