- type: entity
  id: BaseBlock
  abstract: true
  placement:
    mode: SnapgridCenter
  components:
    - type: Sprite
      state: full
      drawdepth: Blocks
    - type: Transform
      anchored: true
    - type: Physics
      bodyType: Static
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.25, -0.25, 0.25, 0.25"
          density: 100
          mask:
            - BlockMask
          layer:
            - BlockLayer
