using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.States.Main.UI;

[GenerateTypedNameReferences]
public sealed partial class MainScreenControl : Control
{
    public MainScreenControl()
    {
        RobustXamlLoader.Load(this);
    }
}