- type: entity
  parent:
    - BaseMobPlatformerController
    - BaseMobPhysics
  id: BaseMob
  abstract: true

# It also requires BaseMobPhysics, or configured Physics and Fixtures components
- type: entity
  id: BaseMobPlatformerController
  abstract: true
  components:
    - type: Input
      context: player
    - type: PlatformerController

- type: entity
  id: BaseMobPhysics
  abstract: true
  components:
    - type: Physics
      bodyType: Dynamic
      friction: 0
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.5
          density: 100
          friction: 0
          mask:
            - MobMask
          layer:
            - MobLayer